### PR TITLE
Add support for Teensy4 boards (__IMXRT1062__)

### PR DESCRIPTION
**Pull request by rjongeneelen**
Added support for Teensy4 boards, specifically __IMXRT1062__.

### CODE REVIEW

**Comment by jandrassy** [comment]
this library is optimized for MCU small SRAM. it uses the smallest TCP stack implementation (UIP) and squeezes all packets in the small 2kbyte memory of the enc28j60. why would you use it Teensy4?

**Comment by rjongeneelen** [comment]
I was looking for a library to support ENC28j60 on my Teensy4, and while testing this library I noticed it didn't compile, hence the pull request to fix it.

Would you suggest a different library to use for Teensy4?

**Comment by jandrassy** [comment]
It is sad, but it looks like there is nothing better. LWIP implementation exists for esp8266 arduino. I don't know if it could be ported. https://github.com/Informatic/espenc

**Comment by rjongeneelen** [comment]
Thank you, appreciated.

**Pull request merged**
